# Generated by Django 4.2 on 2026-04-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_holiday_alter_user_id_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='anomaly_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_anomaly',
            field=models.BooleanField(default=False),
        ),
    ]
