# Generated by Django 4.2 on 2026-05-16 17:35

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_taskcommit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskimage',
            name='image',
            field=models.ImageField(upload_to=core.models.task_image_upload_path),
        ),
    ]
