# Generated by Django 4.2 on 2026-05-24 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_taskimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('BONUS', 'Bonus')], default='BONUS', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(max_length=255)),
                ('month', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_adjustments', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payrolladjustment',
            index=models.Index(fields=['user', 'month'], name='core_payrol_user_id_701435_idx'),
        ),
        migrations.AddIndex(
            model_name='payrolladjustment',
            index=models.Index(fields=['adjustment_type', 'month'], name='core_payrol_adjustm_06e632_idx'),
        ),
    ]
