# Generated by Django 4.2 on 2026-05-27 11:49

from django.db import migrations, models


def backfill_leave_end_dates(apps, schema_editor):
    LeaveRequest = apps.get_model('core', 'LeaveRequest')
    for leave_request in LeaveRequest.objects.filter(end_date__isnull=True):
        leave_request.end_date = leave_request.date
        leave_request.save(update_fields=['end_date'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_chatparticipant_last_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_leave_end_dates, migrations.RunPython.noop),
    ]
