# Generated by Django 4.2 on 2026-05-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_leaverequest_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrolladjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('BONUS', 'Bonus'), ('DEDUCTION', 'Deduction')], default='BONUS', max_length=20),
        ),
    ]
